service: box-list

provider:
  name: aws
  runtime: ruby2.5

  stage: ${opt:stage, self:custom.default_stage}
  region: ${opt:region, self:custom.default_region}

  environment:
    BOX_USER_ID:                  ${env:BOX_USER_ID}
    BOX_JWT_PRIVATE_KEY_PASSWORD: ${env:BOX_JWT_PRIVATE_KEY_PASSWORD}
    BOX_JWT_PRIVATE_KEY_DIR:      input/${opt:stage, self:custom.default_stage}/box_private_key
    BOX_JWT_PUBLIC_KEY_ID:        ${env:BOX_JWT_PUBLIC_KEY_ID}
    BOX_CLIENT_ID:                ${env:BOX_CLIENT_ID}
    BOX_CLIENT_SECRET:            ${env:BOX_CLIENT_SECRET}

custom:
  default_stage: dev
  default_region: us-east-1
  environment:
    dev: ${file(env/dev/env.yml)}
    prd: ${file(env/prd/env.yml)}

functions:
  box:
    handler: box.handler
    environment: ${self:custom.environment.${self:provider.stage}}
    events:
      - schedule: rate(100 minutes)
    timeout: 300
